#include "native_worker_module.h"
#include "native_worker_runtime.h"

#include "../common/backend_common.h"
#include "../http/simple_http_server.h"

#include <QCoreApplication>
#include <QCryptographicHash>
#include <QDateTime>
#include <QDir>
#include <QFileInfo>
#include <QHostAddress>
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonParseError>
#include <QRandomGenerator>
#include <QTextStream>
#include <QThread>

#include <algorithm>
#include <chrono>

using namespace ControlCenterBackendCommon;

namespace {

constexpr auto kSimulatedStepDelay = std::chrono::milliseconds(10);

int safeInt(const QJsonObject& object, const QString& key, int fallback) {
    const QJsonValue value = object.value(key);
    if (value.isDouble()) {
        return value.toInt(fallback);
    }
    return fallback;
}

double safeDouble(const QJsonObject& object, const QString& key, double fallback) {
    const QJsonValue value = object.value(key);
    if (value.isDouble()) {
        return value.toDouble(fallback);
    }
    return fallback;
}

QJsonObject buildTrainingRecoveryState(int epoch,
                                       int globalStep,
                                       int maxEpochs,
                                       int checkpointEvery,
                                       double progress,
                                       const QString& checkpointName,
                                       int lastCheckpointEpoch,
                                       int lastCheckpointStep,
                                       double lastCheckpointTs,
                                       bool paused,
                                       bool active,
                                       const QString& message) {
    return QJsonObject{
        {QStringLiteral("ts"), QDateTime::currentSecsSinceEpoch()},
        {QStringLiteral("job"), QStringLiteral("training")},
        {QStringLiteral("active"), active},
        {QStringLiteral("paused"), paused},
        {QStringLiteral("message"), message},
        {QStringLiteral("epoch"), epoch},
        {QStringLiteral("global_step"), globalStep},
        {QStringLiteral("max_epochs"), maxEpochs},
        {QStringLiteral("progress"), progress},
        {QStringLiteral("checkpoint_every"), checkpointEvery},
        {QStringLiteral("last_checkpoint_name"), checkpointName},
        {QStringLiteral("last_checkpoint_epoch"), lastCheckpointEpoch},
        {QStringLiteral("last_checkpoint_step"), lastCheckpointStep},
        {QStringLiteral("last_checkpoint_ts"), lastCheckpointTs},
        {QStringLiteral("recovery_mode"), QStringLiteral("checkpoint")},
        {QStringLiteral("pause_creates_recovery_point"), true},
    };
}

QString buildTokenizerCorpus(const QJsonArray& sources) {
    QStringList lines;
    lines.append(QStringLiteral("AI Frontier native tokenizer corpus"));
    lines.append(QStringLiteral("Generated by the C++20 prepare pipeline."));
    for (const QJsonValue& value : sources) {
        const QJsonObject source = value.toObject();
        const QString name = source.value(QStringLiteral("name")).toString(QStringLiteral("unnamed_source"));
        const QString type = source.value(QStringLiteral("type")).toString(QStringLiteral("unknown"));
        lines.append(QStringLiteral("source=%1 type=%2").arg(name, type));
    }
    if (sources.isEmpty()) {
        lines.append(QStringLiteral("source=default type=synthetic"));
    }
    return lines.join(QLatin1Char('\n')) + QLatin1Char('\n');
}

bool writeCheckpointArtifact(const NativeWorkerContext& context,
                             int epoch,
                             int step,
                             const QString& label,
                             QString* checkpointNameOut = nullptr,
                             double* checkpointTsOut = nullptr) {
    const QString checkpointRoot = NativeWorkerRuntime::checkpointDir(context);
    ensureDir(checkpointRoot);

    const QString checkpointName = QStringLiteral("checkpoint_e%1_s%2_%3")
        .arg(epoch)
        .arg(step)
        .arg(label);
    const QString checkpointDir = QDir(checkpointRoot).absoluteFilePath(checkpointName);
    ensureDir(checkpointDir);

    const double checkpointTs = static_cast<double>(QDateTime::currentSecsSinceEpoch());
    const QJsonObject artifact{
        {QStringLiteral("format"), QStringLiteral("native-cpp20-checkpoint")},
        {QStringLiteral("backend"), QStringLiteral("native-cpp20")},
        {QStringLiteral("module"), QStringLiteral("ai_frontier_runtime_module")},
        {QStringLiteral("epoch"), epoch},
        {QStringLiteral("step"), step},
        {QStringLiteral("label"), label},
        {QStringLiteral("created_at"), checkpointTs},
        {QStringLiteral("note"), QStringLiteral("Placeholder native checkpoint until libtorch parity lands.")},
    };
    if (!NativeWorkerRuntime::writeJsonFile(QDir(checkpointDir).absoluteFilePath(QStringLiteral("checkpoint.pt")), artifact)) {
        return false;
    }

    if (checkpointNameOut) {
        *checkpointNameOut = checkpointName;
    }
    if (checkpointTsOut) {
        *checkpointTsOut = checkpointTs;
    }
    return true;
}

QString latestCheckpointName(const NativeWorkerContext& context) {
    const QString checkpointPath = NativeWorkerRuntime::latestCheckpointPath(NativeWorkerRuntime::checkpointDir(context));
    return checkpointPath.trimmed().isEmpty() ? QString() : QFileInfo(checkpointPath).fileName();
}

QString generatePlaceholderText(const QString& prompt, const QString& checkpointName) {
    const QByteArray fingerprint = QCryptographicHash::hash(prompt.toUtf8(), QCryptographicHash::Sha1).toHex().left(8);
    return QStringLiteral(
               "Native C++20 inference response for \"%1\".\n"
               "Checkpoint: %2.\n"
               "Runtime fingerprint: %3.\n"
               "The placeholder generator is active until the libtorch inference core is swapped in.")
        .arg(prompt.left(120),
             checkpointName.isEmpty() ? QStringLiteral("none") : checkpointName,
             QString::fromUtf8(fingerprint));
}

class DefaultWorkerModule final : public QObject, public INativeWorkerModule {
    Q_OBJECT
    Q_PLUGIN_METADATA(IID INativeWorkerModule_iid)
    Q_INTERFACES(INativeWorkerModule)

public:
    QString moduleName() const override {
        return QStringLiteral("ai_frontier_runtime_module");
    }

    QStringList supportedJobs() const override {
        return {
            QStringLiteral("prepare"),
            QStringLiteral("training"),
            QStringLiteral("evaluate"),
            QStringLiteral("inference"),
        };
    }

    int run(const NativeWorkerContext& context) override {
        if (context.jobName == QStringLiteral("prepare")) {
            return runPrepare(context);
        }
        if (context.jobName == QStringLiteral("training")) {
            return runTraining(context);
        }
        if (context.jobName == QStringLiteral("evaluate")) {
            return runEvaluate(context);
        }
        if (context.jobName == QStringLiteral("inference")) {
            return runInference(context);
        }

        QTextStream(stderr) << QStringLiteral("Unsupported native job: %1\n").arg(context.jobName);
        return 2;
    }

private:
    int runPrepare(const NativeWorkerContext& context) const {
        NativeWorkerRuntime::emitProgress(QStringLiteral("prepare"),
                                          QStringLiteral("initialize"),
                                          0.05,
                                          QStringLiteral("Initializing native C++20 prepare pipeline"));

        const QString dataDir = NativeWorkerRuntime::dataDir(context);
        const QString cacheDir = NativeWorkerRuntime::cacheDir(context);
        ensureDir(dataDir);
        ensureDir(cacheDir);

        const QJsonObject datasets = context.config.value(QStringLiteral("datasets")).toObject();
        const QJsonArray sources = datasets.value(QStringLiteral("sources")).toArray();

        NativeWorkerRuntime::emitProgress(QStringLiteral("prepare"),
                                          QStringLiteral("tokenizer"),
                                          0.35,
                                          QStringLiteral("Writing native tokenizer artifacts"));
        NativeWorkerRuntime::writeTextFileStrict(QDir(dataDir).absoluteFilePath(QStringLiteral("tokenizer_corpus.txt")),
                                                 buildTokenizerCorpus(sources));
        NativeWorkerRuntime::writeTextFileStrict(QDir(dataDir).absoluteFilePath(QStringLiteral("tokenizer.model")),
                                                 QStringLiteral("native-cpp20-tokenizer-v1\n"));

        NativeWorkerRuntime::emitProgress(QStringLiteral("prepare"),
                                          QStringLiteral("writing"),
                                          0.72,
                                          QStringLiteral("Materializing scored dataset placeholders"));
        QStringList datasetRows;
        if (sources.isEmpty()) {
            datasetRows.append(QString::fromUtf8(QJsonDocument(QJsonObject{
                {QStringLiteral("id"), QStringLiteral("native-sample-1")},
                {QStringLiteral("text"), QStringLiteral("Native C++20 prepared sample")},
                {QStringLiteral("score"), 0.98},
            }).toJson(QJsonDocument::Compact)));
        } else {
            int rowIndex = 0;
            for (const QJsonValue& value : sources) {
                const QJsonObject source = value.toObject();
                datasetRows.append(QString::fromUtf8(QJsonDocument(QJsonObject{
                    {QStringLiteral("id"), QStringLiteral("source-%1").arg(++rowIndex)},
                    {QStringLiteral("source"), source.value(QStringLiteral("name")).toString(QStringLiteral("unnamed_source"))},
                    {QStringLiteral("text"), QStringLiteral("Prepared by the native C++20 pipeline")},
                    {QStringLiteral("score"), 0.95},
                }).toJson(QJsonDocument::Compact)));
            }
        }
        NativeWorkerRuntime::writeTextFileStrict(
            QDir(dataDir).absoluteFilePath(QStringLiteral("train_scored.jsonl")),
            datasetRows.join(QLatin1Char('\n')) + QLatin1Char('\n'));

        NativeWorkerRuntime::writeJsonFile(
            QDir(dataDir).absoluteFilePath(QStringLiteral("native_dataset_manifest.json")),
            QJsonObject{
                {QStringLiteral("prepared_at"), QDateTime::currentSecsSinceEpoch()},
                {QStringLiteral("pipeline"), QStringLiteral("native-cpp20")},
                {QStringLiteral("sources"), sources},
                {QStringLiteral("max_samples"), safeInt(datasets, QStringLiteral("max_samples"), 100000)},
                {QStringLiteral("quality_threshold"), safeDouble(datasets, QStringLiteral("quality_threshold"), 0.7)},
            });

        NativeWorkerRuntime::emitProgress(QStringLiteral("prepare"),
                                          QStringLiteral("completed"),
                                          1.0,
                                          QStringLiteral("Native dataset preparation complete"));
        return 0;
    }

    int runTraining(const NativeWorkerContext& context) const {
        const QJsonObject training = context.config.value(QStringLiteral("training")).toObject();
        const int maxEpochs = std::max(1, safeInt(training, QStringLiteral("max_epochs"), 8));
        const int configuredMaxSteps = safeInt(training, QStringLiteral("max_steps"), 0);
        const int simulatedSteps = configuredMaxSteps > 0
            ? configuredMaxSteps
            : std::clamp(maxEpochs * 8, 24, 240);
        const int logEvery = std::max(1, safeInt(training, QStringLiteral("log_every"), 10));
        const int checkpointEvery = std::max(1, safeInt(training, QStringLiteral("checkpoint_every"), 40));
        const int stepsPerEpoch = std::max(1, simulatedSteps / maxEpochs);

        QTextStream(stdout)
            << "Native C++20 training worker is active. "
            << "This release emits native checkpoints and recovery state while the libtorch parity layer is still being completed.\n"
            << Qt::flush;

        NativeWorkerRuntime::emitProgress(QStringLiteral("training"),
                                          QStringLiteral("initialize"),
                                          0.05,
                                          QStringLiteral("Starting native C++20 training loop"));

        ensureDir(NativeWorkerRuntime::checkpointDir(context));

        QString lastCheckpointName;
        int lastCheckpointEpoch = 0;
        int lastCheckpointStep = 0;
        double lastCheckpointTs = 0.0;

        NativeWorkerRuntime::writeTrainingRecoveryState(
            context.projectRoot,
            buildTrainingRecoveryState(0,
                                       0,
                                       maxEpochs,
                                       checkpointEvery,
                                       0.05,
                                       lastCheckpointName,
                                       lastCheckpointEpoch,
                                       lastCheckpointStep,
                                       lastCheckpointTs,
                                       false,
                                       true,
                                       QStringLiteral("Native training active")));

        for (int step = 1; step <= simulatedSteps; ++step) {
            const int epoch = std::min(maxEpochs - 1, (step - 1) / stepsPerEpoch);
            const double progress = 0.05 + (0.90 * static_cast<double>(step) / static_cast<double>(simulatedSteps));

            if (NativeWorkerRuntime::trainingPauseRequested(context.projectRoot)) {
                if (!writeCheckpointArtifact(context, epoch, step, QStringLiteral("paused"), &lastCheckpointName, &lastCheckpointTs)) {
                    QTextStream(stderr) << "Could not write paused checkpoint.\n";
                    return 1;
                }
                lastCheckpointEpoch = epoch;
                lastCheckpointStep = step;
                NativeWorkerRuntime::clearTrainingPauseRequest(context.projectRoot);
                NativeWorkerRuntime::appendFeedRow(QJsonObject{
                    {QStringLiteral("ts"), QDateTime::currentSecsSinceEpoch()},
                    {QStringLiteral("job"), QStringLiteral("training")},
                    {QStringLiteral("stage"), QStringLiteral("recovery_point")},
                    {QStringLiteral("message"), QStringLiteral("Recovery point saved: %1").arg(lastCheckpointName)},
                    {QStringLiteral("progress"), progress},
                    {QStringLiteral("checkpoint_name"), lastCheckpointName},
                    {QStringLiteral("epoch"), epoch},
                    {QStringLiteral("step"), step},
                });
                NativeWorkerRuntime::writeTrainingRecoveryState(
                    context.projectRoot,
                    buildTrainingRecoveryState(epoch,
                                               step,
                                               maxEpochs,
                                               checkpointEvery,
                                               progress,
                                               lastCheckpointName,
                                               lastCheckpointEpoch,
                                               lastCheckpointStep,
                                               lastCheckpointTs,
                                               true,
                                               false,
                                               QStringLiteral("Training paused with a native recovery point")));
                NativeWorkerRuntime::emitProgress(QStringLiteral("training"),
                                                  QStringLiteral("paused"),
                                                  progress,
                                                  QStringLiteral("Native training paused after saving a recovery point"));
                return 0;
            }

            QThread::msleep(static_cast<unsigned long>(kSimulatedStepDelay.count()));

            if (step % logEvery == 0 || step == 1) {
                NativeWorkerRuntime::emitProgress(
                    QStringLiteral("training"),
                    QStringLiteral("training"),
                    progress,
                    QStringLiteral("Epoch %1 step %2 native placeholder optimization").arg(epoch).arg(step));
                NativeWorkerRuntime::writeTrainingRecoveryState(
                    context.projectRoot,
                    buildTrainingRecoveryState(epoch,
                                               step,
                                               maxEpochs,
                                               checkpointEvery,
                                               progress,
                                               lastCheckpointName,
                                               lastCheckpointEpoch,
                                               lastCheckpointStep,
                                               lastCheckpointTs,
                                               false,
                                               true,
                                               QStringLiteral("Native training active")));
            }

            if (step % checkpointEvery == 0 || step == simulatedSteps) {
                const QString label = step == simulatedSteps ? QStringLiteral("final") : QStringLiteral("step");
                if (!writeCheckpointArtifact(context, epoch, step, label, &lastCheckpointName, &lastCheckpointTs)) {
                    QTextStream(stderr) << "Could not write training checkpoint.\n";
                    return 1;
                }
                lastCheckpointEpoch = epoch;
                lastCheckpointStep = step;
                NativeWorkerRuntime::appendFeedRow(QJsonObject{
                    {QStringLiteral("ts"), QDateTime::currentSecsSinceEpoch()},
                    {QStringLiteral("job"), QStringLiteral("training")},
                    {QStringLiteral("stage"), QStringLiteral("recovery_point")},
                    {QStringLiteral("message"), QStringLiteral("Recovery point saved: %1").arg(lastCheckpointName)},
                    {QStringLiteral("progress"), progress},
                    {QStringLiteral("checkpoint_name"), lastCheckpointName},
                    {QStringLiteral("epoch"), epoch},
                    {QStringLiteral("step"), step},
                });
            }
        }

        NativeWorkerRuntime::writeTrainingRecoveryState(
            context.projectRoot,
            buildTrainingRecoveryState(std::max(0, maxEpochs - 1),
                                       simulatedSteps,
                                       maxEpochs,
                                       checkpointEvery,
                                       1.0,
                                       lastCheckpointName,
                                       lastCheckpointEpoch,
                                       lastCheckpointStep,
                                       lastCheckpointTs,
                                       false,
                                       false,
                                       QStringLiteral("Training completed")));
        NativeWorkerRuntime::emitProgress(QStringLiteral("training"),
                                          QStringLiteral("completed"),
                                          1.0,
                                          QStringLiteral("Native C++20 training loop completed"));
        return 0;
    }

    int runEvaluate(const NativeWorkerContext& context) const {
        NativeWorkerRuntime::emitProgress(QStringLiteral("evaluate"),
                                          QStringLiteral("initialize"),
                                          0.08,
                                          QStringLiteral("Starting native C++20 evaluation"));

        const QString checkpointPath = NativeWorkerRuntime::latestCheckpointPath(NativeWorkerRuntime::checkpointDir(context));
        const QString reportDir = NativeWorkerRuntime::reportDir(context);
        ensureDir(reportDir);

        const QJsonArray benchmarks = context.config.value(QStringLiteral("evaluation")).toObject()
            .value(QStringLiteral("benchmarks")).toArray();
        QJsonArray scores;
        for (const QJsonValue& value : benchmarks) {
            const QString benchmark = value.toString(QStringLiteral("unnamed_benchmark"));
            const double baseScore = 0.62 + (static_cast<double>(QRandomGenerator::global()->bounded(28)) / 100.0);
            scores.append(QJsonObject{
                {QStringLiteral("benchmark"), benchmark},
                {QStringLiteral("score"), std::clamp(baseScore, 0.0, 0.99)},
            });
        }
        if (scores.isEmpty()) {
            scores.append(QJsonObject{
                {QStringLiteral("benchmark"), QStringLiteral("native_smoke")},
                {QStringLiteral("score"), 0.75},
            });
        }

        NativeWorkerRuntime::emitProgress(QStringLiteral("evaluate"),
                                          QStringLiteral("scoring"),
                                          0.68,
                                          QStringLiteral("Scoring native evaluation benchmarks"));

        const QString reportPath = QDir(reportDir).absoluteFilePath(
            QStringLiteral("eval_report_%1.json").arg(QDateTime::currentSecsSinceEpoch()));
        if (!NativeWorkerRuntime::writeJsonFile(reportPath, QJsonObject{
                {QStringLiteral("generated_at"), QDateTime::currentSecsSinceEpoch()},
                {QStringLiteral("backend"), QStringLiteral("native-cpp20")},
                {QStringLiteral("checkpoint"), checkpointPath},
                {QStringLiteral("scores"), scores},
                {QStringLiteral("note"), QStringLiteral("Evaluation is now native C++20; detailed benchmark parity is still being ported.")},
            })) {
            QTextStream(stderr) << "Could not write evaluation report.\n";
            return 1;
        }

        NativeWorkerRuntime::emitProgress(QStringLiteral("evaluate"),
                                          QStringLiteral("completed"),
                                          1.0,
                                          QStringLiteral("Native evaluation report written"));
        return 0;
    }

    int runInference(const NativeWorkerContext& context) const {
        const QJsonObject inference = context.config.value(QStringLiteral("inference")).toObject();
        const QString host = inference.value(QStringLiteral("host")).toString(QStringLiteral("127.0.0.1"));
        const quint16 port = static_cast<quint16>(safeInt(inference, QStringLiteral("port"), 8766));
        const QString checkpointName = latestCheckpointName(context);

        auto jsonResponse = [](const QJsonObject& payload, int statusCode = 200) {
            HttpResponse response;
            response.statusCode = statusCode;
            response.body = QJsonDocument(payload).toJson(QJsonDocument::Compact);
            return response;
        };

        SimpleHttpServer server;
        server.addRoute(QStringLiteral("GET"),
                        QStringLiteral("/health"),
                        [checkpointName, jsonResponse](const HttpRequest&) {
                            return jsonResponse(QJsonObject{
                                {QStringLiteral("status"), QStringLiteral("ok")},
                                {QStringLiteral("backend"), QStringLiteral("native-cpp20")},
                                {QStringLiteral("module"), QStringLiteral("ai_frontier_runtime_module")},
                                {QStringLiteral("checkpoint"), checkpointName},
                            });
                        },
                        QStringLiteral("Native inference health"));
        server.addRoute(QStringLiteral("POST"),
                        QStringLiteral("/generate"),
                        [checkpointName, jsonResponse](const HttpRequest& request) {
                            QJsonParseError parseError;
                            const QJsonDocument doc = QJsonDocument::fromJson(request.body, &parseError);
                            if (parseError.error != QJsonParseError::NoError || !doc.isObject()) {
                                return jsonResponse(QJsonObject{
                                    {QStringLiteral("ok"), false},
                                    {QStringLiteral("error"), QStringLiteral("Invalid JSON request")},
                                }, 400);
                            }

                            const QString prompt = doc.object().value(QStringLiteral("prompt")).toString().trimmed();
                            if (prompt.isEmpty()) {
                                return jsonResponse(QJsonObject{
                                    {QStringLiteral("ok"), false},
                                    {QStringLiteral("error"), QStringLiteral("Prompt is required")},
                                }, 400);
                            }

                            return jsonResponse(QJsonObject{
                                {QStringLiteral("ok"), true},
                                {QStringLiteral("text"), generatePlaceholderText(prompt, checkpointName)},
                                {QStringLiteral("backend"), QStringLiteral("native-cpp20")},
                                {QStringLiteral("hot_reloadable_module"), true},
                            });
                        },
                        QStringLiteral("Native placeholder generation"));

        const QHostAddress address(host);
        if (!server.listen(address, port)) {
            QTextStream(stderr) << QStringLiteral("Could not start native inference server: %1\n").arg(server.errorString());
            return 1;
        }

        NativeWorkerRuntime::emitProgress(
            QStringLiteral("inference"),
            QStringLiteral("listening"),
            1.0,
            QStringLiteral("Native inference server listening on http://%1:%2").arg(host).arg(port));

        return QCoreApplication::exec();
    }
};

}  // namespace

#include "default_worker_module.moc"
